backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: 'locations'
    label: 'Locations'
    folder: 'src/content/locations'
    create: true
    editor:
      preview: false
    fields:
      [
        { label: Title, name: title, widget: string },
        {
          label: 'Address',
          name: 'address',
          widget: 'object',
          collapsed: true,
          summary: '{{fields.street}}, {{fields.post-code}} {{fields.city}}',
          fields:
            [
              { label: 'Street + Number', name: 'street', widget: 'string' },
              { label: 'City', name: 'city', widget: 'string' },
              { label: 'Postal Code', name: 'post-code', widget: 'string' },
            ],
        },
        {
          label: 'Sections',
          name: 'sections',
          widget: 'list',
          minimize_collapsed: false,
          summary: '{{section}}',
          add_to_top: true,
          field:
            {
              label: 'Section',
              name: 'section',
              widget: 'relation',
              collection: 'sections',
              value_field: '{{slug}}',
              display_fields: ['{{title}}'],
              search_fields: ['title'],
            },
        },
      ]
  - name: 'sections'
    label: 'Sections'
    folder: 'src/content/sections'
    editor:
      preview: false
    create: true
    fields:
      [
        { label: Title, name: title, widget: string },
        { label: Tagline, name: tagline, widget: string },
        { label: Gold, name: gold, widget: boolean, default: false },
        { label: Width, name: width, widget: number, default: 6 },
        { label: height, name: height, widget: number, default: 3 },
        { label: Content(EN), name: contentEN, widget: markdown },
        { label: Content(NL), name: contentNL, widget: markdown },
      ]
