backend:
  # name: test-repo
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/content/calendar-page.md'
        label: 'Calendar'
        name: 'calendar'
        fields: [
          {
            label: 'Template Key',
            name: 'templateKey',
            widget: 'hidden',
            default: 'calendar-page',
          },
          {
            label: Events,
            name: events,
            widget: list,
            fields: [
              { label: Name, name: title, widget: string },
              { label: Date, name: date, widget: date },
              { label: End Date, name: end-date, widget: date, required: false },
              { label: Type, name: type, widget: string },
              {
                label: Description,
                name: description,
                widget: string,
              },
            ],
          },
        ]